spring.application.name=Reporteapi

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/reporte_api
spring.datasource.username=root
spring.datasource.password=Antartida002?.hola


